### ISSUE TITLE
Room Type Report

### ISSUE THREAD

**Issue by LBeghini** [eppica/Hotel-Management-System#93]
When I tried to create a report with empty values, it returned an page with 500 error.

## Steps

- Reports
- Room Types Report
- Submit (without filling anything)

<img src="https://user-images.githubusercontent.com/37659479/103471185-d07abf00-4d5b-11eb-98ef-d31c38271b77.png" width=600/>

## Error

```
Jan 03, 2021 12:31:18 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [ReportsController] in context with path [] threw exception
java.lang.NumberFormatException
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:625)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:402)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:835)
	at controller.ReportsController.doPost(ReportsController.java:128)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:452)
	... 23 more

```

**Comment by LBeghini** [comment]
The problem was that the request was sending an empty string, and not a null value. But, when that was fixed, the report appeared with no data to show
